### ISSUE TITLE
blue dragon story map thumbnail

### ISSUE THREAD

**Issue by fethomps** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#639]
The thumbnail image used to launch the blue dragon interactive story map has gray outlines of Arkansas, Mississippi, and other states superimposed on top of the Lower Colorado River Basin.  Can someone replace it with a new screenshot?

**Comment by jread-usgs** [comment]
@fethomps do you have a screenshot we could use for that?

**Comment by jread-usgs** [comment]
@mwernimont see 
![image](https://cloud.githubusercontent.com/assets/2349007/11848343/79ed5756-a3e7-11e5-8889-3585df6367c2.png)
as a replacement?

**Comment by fethomps** [comment]
The image above looks good.

**Comment by mwernimont** [comment]
![screen shot 2015-12-16 at 11 36 44 am](https://cloud.githubusercontent.com/assets/6390096/11848729/9ff0021c-a3e9-11e5-9623-e2d72a2e92cb.png)


new thumbnail for the blue dragon explore more

**Comment by mwernimont** [comment]
look good?

**Comment by jread-usgs** [comment]
:-1:

**Comment by mwernimont** [comment]
why?!

**Comment by jread-usgs** [comment]
typo

**Comment by fethomps** [comment]
The one I see is realtime.  Think it should be real-time.

**Comment by mwernimont** [comment]
Can be fixed, but just in terms of the pic are you guys satisfied?

**Comment by jread-usgs** [comment]
yes. I am

**Comment by fethomps** [comment]
i am too
