### ISSUE TITLE
Leer Mas turns to English after clicked

### ISSUE THREAD

**Issue by mwernimont** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#661]
Probably my poor coding, but @jiwalker-usgs how do you suggest to avoid the Leer Mas on the site tuning into Read More after you click it?

**Comment by jiwalker-usgs** [comment]
I'll have to take a look, but we should template this text in somehow.

**Comment by eread-usgs** [comment]
Fixed.....
