### ISSUE TITLE
wrap text on Mead projection

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#669]
As is, it runs off the edge of the screen.

![screen shot 2016-05-18 at 2 43 06 pm](https://cloud.githubusercontent.com/assets/7794368/15372619/ebd1abae-1d06-11e6-85a4-bfec1c79ca31.png)

**Comment by eread-usgs** [comment]
@jiwalker-usgs this is another one @jread-usgs hoped you could look into

**Comment by jiwalker-usgs** [comment]
#685 should fix this

**Comment by eread-usgs** [comment]
Top two are good, third one down not wrapping....

![screen shot 2016-05-23 at 1 51 37 pm](https://cloud.githubusercontent.com/assets/7794368/15479483/6dd9a92c-20ee-11e6-894c-f85752b2e258.png)

**Comment by jiwalker-usgs** [comment]
weird, looks fine on mine 

![image](https://cloud.githubusercontent.com/assets/1173041/15482671/89c5c4b0-20f6-11e6-96eb-136044c7136b.png)

I'll bump it onto a second line

**Comment by jread-usgs** [comment]
Zoom level of browser?

**Comment by jiwalker-usgs** [comment]
mine is 100%

**Comment by jiwalker-usgs** [comment]
https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/pull/686

**Comment by jread-usgs** [comment]
mark of the 😈

**Comment by jread-usgs** [comment]
I guess I need better 👓

**Comment by eread-usgs** [comment]
thx @jiwalker-usgs
