### ISSUE TITLE
Check out new Spanish language site on mobile/tablet

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#670]
@mwernimont Make a list of things that don't look right here https://cida-test.er.usgs.gov/bluedragon/dev/es/#Introduction

Fix if you can or document for @jread-usgs or @jiwalker-usgs

**Comment by mwernimont** [comment]
I don't see any huge issues like graphs or buttons not working. There are a few odd text wraps due to the language difference and the amount of letters in words, which I don't think is too bad. Am I missing something @eread-usgs ? There been complaints of something that I am overlooking?

**Comment by jread-usgs** [comment]
Nope, those are the issues. We may need to adjust the css on those classes for that version. I will take a crack at it I hope.

**Comment by mwernimont** [comment]
So @jread-usgs You want this ticket? or..? I don't wanna run into merge conflicts if you are taking a crack at it

**Comment by mwernimont** [comment]
![screen shot 2016-05-24 at 9 35 43 am](https://cloud.githubusercontent.com/assets/6390096/15507949/3493e40c-2193-11e6-8e4e-76b89b63b9e5.png)

**Comment by mwernimont** [comment]
Got the spanish nav tooltips to not wrap and look normal

**Comment by eread-usgs** [comment]
@mwarren-USGS and @jread-usgs let me know if you think this one is wrapped up and we can close it.

**Comment by mwernimont** [comment]
@eread-usgs I don't think my @mwernimont pops up, but doubt Meredith wants to be notified of these tickets ;)

**Comment by eread-usgs** [comment]
lol @mwernimont and @jread-usgs are we done on this one?

**Comment by mwernimont** [comment]
To me it is, it was the only thing I really saw that was disturbing. @jread-usgs anything else we need to address?

**Comment by mwernimont** [comment]
will do

On Tue, May 24, 2016 at 10:42 AM, Emily Read <notifications@github.com>
wrote:

> lol @mwernimont <https://github.com/mwernimont> and @jread-usgs
> <https://github.com/jread-usgs> are we done on this one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/issues/670#issuecomment-221313198>
>



-- 
[image: Lynxnet, LLC] Marty Wernimont | Web Designer Jr
Lynxnet, LLC | 8505 Research Way, Middleton, WI 53562
Office:608-821-3839 | Cell: 507-301-2496 | Marty.Wernimont@lynxnetllc.com

Confidentiality Notice: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, copy, use, disclosure,
or distribution is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply e-mail and destroy all copies
of the original message.
