### ISSUE TITLE
Utah caption doesn't appear on espanol version

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#671]
@jiwalker-usgs take a look and let us know how to fix?

![screen shot 2016-05-18 at 2 45 46 pm](https://cloud.githubusercontent.com/assets/7794368/15372689/42751a5e-1d07-11e6-84c8-e7f75ae63b0d.png)

**Comment by jiwalker-usgs** [comment]
The utah.svg is the same between the english and spanish versions of the page.  The characters are SVG paths, so we will have to switch to a text element in order to use the translation text.

**Comment by jiwalker-usgs** [comment]
@mwernimont I'll work this up if you could take a look and make it look good.

**Comment by jiwalker-usgs** [comment]
I misread this actually, this is about the caption below.  This was split into two keys (imperial, metric), so there is no `coBasinReservoir4` key anymore.  We can probably just merge these into one key as there isn't an imperial spanish version nor a metric english version.
