### ISSUE TITLE
Remove hard coding of text on Utah figure, so spanish translation....

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#672]
Remove hard coding of text on Utah figure, so spanish translation can be applied. This is the tag for it:

```
<coBasinReservoir3>
``` 

![screen shot 2016-05-18 at 2 45 46 pm](https://cloud.githubusercontent.com/assets/7794368/15372766/a42d2822-1d07-11e6-841f-49e188a8f8e5.png)

**Comment by jiwalker-usgs** [comment]
https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/pull/683 templates in the text, but some work on the content and style is needed.

**Comment by eread-usgs** [comment]
I merged #683 and I could strangely see the spanish text that goes next to the state icon when the page was loading, but not after it completed loading.... @mwernimont ??

**Comment by mwernimont** [comment]
@jiwalker-usgs Do we really need to say Utah under a foot of water, when the text underneath says it and the state is labeled?

**Comment by mwernimont** [comment]
@eread-usgs What version of the app were you seeing the strange loading on the utah fig? I'm testing on my local version and not seeing it.

**Comment by eread-usgs** [comment]
on dev @mwernimont - its not that big of a deal, there are a few other odd things i see happen when the page is loading.I just mentioned that b/c I could see the spanish text in there.... but just not once the page loaded.

**Comment by eread-usgs** [comment]
And I think its fine to just remove the text on es if its not possible to make it fit or whatever. @mwernimont  @jiwalker-usgs

**Comment by eread-usgs** [comment]
KISS keep it simple!

**Comment by mwernimont** [comment]
@eread-usgs I got it to fit, github is tweaking a little bit with showing the PR was merged, but the solution should be in the code soon.

**Comment by eread-usgs** [comment]
ok, thx @mwernimont  I'll check it out later today
