### ISSUE TITLE
Read more buttons not working quite right: espanol

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#673]
@mwernimont  needs some love...

Some Read More buttons work just right: 

![screen shot 2016-05-18 at 2 49 58 pm](https://cloud.githubusercontent.com/assets/7794368/15372813/eb22b21a-1d07-11e6-9f33-d58668f164f0.png)

Other one's show a 'Read More' button even after being pushed:

![screen shot 2016-05-18 at 2 50 16 pm](https://cloud.githubusercontent.com/assets/7794368/15372807/e843fa36-1d07-11e6-99d1-add1f6807820.png)

And those same ones, if you click the Read More button after you have already expanded it, then show a 'Hide Text', even though the text is already hidden.

![screen shot 2016-05-18 at 2 50 21 pm](https://cloud.githubusercontent.com/assets/7794368/15372802/e51bf994-1d07-11e6-930d-f000e748afbd.png)

**Comment by eread-usgs** [comment]
related to: https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/issues/661

**Comment by mwernimont** [comment]
@eread-usgs Will be fixed with PR #677

**Comment by eread-usgs** [comment]
Thanks!! @mwernimont
