### ISSUE TITLE
Check out Spanish site on Firefox and IE

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#688]
@mwernimont take a look???

**Comment by mwernimont** [comment]
@eread-usgs So looked at the spanish version on FF, IE11, and IE10. Everything looked fine to me. I didn't read the site word for word, but all the buttons work, its all in spanish, and the tooltips all look good.

**Comment by eread-usgs** [comment]
thx @mwernimont
