### ISSUE TITLE
release may data?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#689]
A branch w/o the translation but w/ the data updates is here: https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/tree/data_updates

Should we release?

**Comment by jread-usgs** [comment]
Here is the comparison between the March release and the data update branch
https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/compare/4f301c18d93a60dd78c6b6d049f3fa4e11dc4cf7...87231858661e646a3597100763cae842a785453d

**Comment by jread-usgs** [comment]
@jiwalker-usgs thoughts on releasing?

**Comment by jiwalker-usgs** [comment]
I think we are about on schedule for an update

**Comment by eread-usgs** [comment]
Yes, @jiwalker-usgs if you could merge (not sure if that's what you do for a branch) and promote to the DOI production app that would be greatly appreciated.
