### ISSUE TITLE
one last 'read more' showing up in es version

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#693]
Below LMAF figure caption, for the last caption (last click) 
![screen shot 2016-06-07 at 3 34 30 pm](https://cloud.githubusercontent.com/assets/7794368/15872053/83056dc6-2cc5-11e6-83e1-8ec649fd1622.png)

**Comment by mwernimont** [comment]
@eread-usgs should be good with #695

**Comment by eread-usgs** [comment]
still seeing it.... 
![screen shot 2016-06-07 at 9 16 10 pm](https://cloud.githubusercontent.com/assets/7794368/15879801/2de90106-2cf5-11e6-84b0-e2f58cd3b83e.png)

![screen shot 2016-06-07 at 9 16 19 pm](https://cloud.githubusercontent.com/assets/7794368/15879803/33c4eb30-2cf5-11e6-94cf-dfc18746103a.png)

**Comment by mwernimont** [comment]
@eread-usgs apologies, #696 takes care of the rest of them.

**Comment by eread-usgs** [comment]
hmmmmm @mwernimont  still seeing it on dev- looks like you ran the jenkins job after you merged the code. ...??
![screen shot 2016-06-08 at 9 42 06 am](https://cloud.githubusercontent.com/assets/7794368/15896229/5dd05c3a-2d5d-11e6-93e4-1a06fc33332a.png)

**Comment by mwernimont** [comment]
I did not, I always just assume we have it set up for jenkins to run after a merge

**Comment by eread-usgs** [comment]
ok, i just ran it again just in case. I wonder why it appears fixed to you @mwernimont  but not on dev? @jiwalker-usgs thoughts?

**Comment by mwernimont** [comment]
sigh... @eread-usgs I'm sorry, I forgot about the dumb R Render thing you gotta do. Will be up soon

**Comment by eread-usgs** [comment]
ok ;)

**Comment by eread-usgs** [comment]
@mwernimont , now the button doesn't work at all. I still get the cursor with the little pointed finger, as if it is a link, but it doesn't do anything...

**Comment by mwernimont** [comment]
Well I've made this as painful as possible it seems, but fingers crossed, everything should be working.

**Comment by eread-usgs** [comment]
hurray!!!!
![screen shot 2016-06-08 at 11 09 33 am](https://cloud.githubusercontent.com/assets/7794368/15899382/8528d29c-2d69-11e6-91c0-1a6c1c1ce68e.png)
