### ISSUE TITLE
deploy changes on dev, then push to production

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis#703]
After this issue (https://github.com/USGS-CIDA/OWDI-Lower-Colorado-Drought-Vis/issues/702) is complete

**Comment by jread-usgs** [comment]
@jiwalker-usgs pending merge on #704 , this is ready to go

**Comment by eread-usgs** [comment]
merged @jiwalker-usgs. I believe this is ready to push through to test and production- if you could look through it on the DOI cloud test site before pushing it up to the DOI prod that would be great. Thank you!

**Comment by jiwalker-usgs** [comment]
Will do, looking at it on internal dev now

**Comment by jiwalker-usgs** [comment]
looks good, @eread-usgs are we still holding off on deploying the Spanish language site to the IBM cloud?

**Comment by jiwalker-usgs** [comment]
I pushed these changes to production, note though that the tag (v1.0.5) doesn't match the version (v1.1.0) that is contained in the project.  This is an oversight that can be addressed with the next update.
